version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chatbot-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  # For local development only - NOT FOR PRODUCTION
  # In production, use Supabase hosted service
  # This is just for local testing
  db:
    image: supabase/postgres:14.1.0
    container_name: ai-chatbot-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: 